//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bifrost.Launcher {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bifrost.Launcher.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 942464121E433F5FFF0389B6015B296F8411D341	1.9.0.614
        ///82F8D87C2E780A3491B4EC49575B2542DE2F0375	1.9.0.645
        ///3E70AE41398D44836BFFE1971B728DF67E35568C	1.0.2447.0
        ///0961DE7BA206421D087D45D0521E291F4B885389	1.0.2470.0
        ///6467E9AF671796C9ECBBB568A9CB8B707D0B8DFD	1.10.1.1
        ///4D394193827D09B1A2F0CC93143998FBFC835FD5	1.10.0.45
        ///201504471BEDF04B263EF64439D86981FAE4B322	1.10.0.66
        ///4A4B6E6EF14B9F5F5D3DD193CA6ED4625F62E61C	1.10.0.69
        ///9D3C32A42EB7455C042D8C7A2BCE2C7607FF1965	1.10.0.68
        ///F1C99B3DF9B57B5490F7E124D9183B6F90BA491D	1. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ClientMetadataTable {
            get {
                return ResourceManager.GetString("ClientMetadataTable", resourceCulture);
            }
        }
    }
}
